name: CI

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Clean install
      run: |
        rm -rf node_modules package-lock.json
        npm install
    
    - name: Create custom build script
      run: |
        # Create a shell script to run build with --no-minify flag
        cat > build.sh << 'EOF'
        #!/bin/bash
        npx vite build --minify=false
        EOF
        chmod +x build.sh
    
    - name: Build project
      run: |
        # Run the custom build script
        ./build.sh
        
        # Create .nojekyll file after build
        touch dist/.nojekyll
        # Copy 404.html to dist
        cp 404.html dist/
        # Copy HTML files directly to dist
        cp education.html consultancy.html about.html contact.html dist/
        # Ensure forms directory exists and copy forms
        mkdir -p dist/forms
        cp forms/*.html dist/forms/
        # Ensure courses directory exists and copy courses
        mkdir -p dist/courses
        cp courses/*.html dist/courses/
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: dist/
        retention-days: 7
        
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        clean-exclude: |
          .nojekyll
