name: Deploy to GitHub Pages

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

# Permissions needed for GitHub Pages
permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    container: node:18-alpine
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Install dependencies
      run: npm install
    
    - name: Build project
      run: npm run build
    - name: Install git
      run: apk add --no-cache git

      
    - name: Prepare for GitHub Pages
      run: |
        # Create .nojekyll file to disable Jekyll processing
        touch dist/.nojekyll
        
        # Create empty README in dist to help GitHub Pages
        echo "# System3 Website" > dist/README.md
    
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: gh-pages
        clean: true
