name: Deploy to Staging

on:
  push:
    branches: [ develop ]
  workflow_run:
    workflows: ["CI"]
    branches: [ develop ]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    - name: Install Terser (required by Vite for minification)
      run: npm install terser --save-dev
    
    - name: Build project
      run: npm run build
    
    - name: Deploy to GitHub Pages (Staging)
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        token: ${{ secrets.GH_DEPLOY_PAT }}
        folder: dist
        branch: gh-pages
        target-folder: staging
        clean: true
        
    - name: Create deployment comment
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const stagingUrl = 'https://${{ github.repository_owner }}.github.io/${{ github.event.repository.name }}/staging/';
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `🚀 Staging deployment complete! View it at: [${stagingUrl}](${stagingUrl})`
          })
      if: github.event_name == 'pull_request'
